//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemate_Matching
{


    public partial class userAttributes
    {

        protected global::System.Web.UI.WebControls.TextBox txtGender; // Keep this hidden textbox
        // The individual RadioButton controls are removed from designer as they are HTML inputs
        // protected global::System.Web.UI.WebControls.RadioButton genderMale;
        // protected global::System.Web.UI.WebControls.RadioButton genderFemale;

        protected global::System.Web.UI.WebControls.DropDownList ddlSleepSchedule; // New DropDownList for Sleep Schedule
        protected global::System.Web.UI.WebControls.CheckBox chkSmoker;
        protected global::System.Web.UI.WebControls.CheckBox chkDrinker;
        protected global::System.Web.UI.WebControls.TextBox txtHygiene;
        protected global::System.Web.UI.WebControls.TextBox txtNoisiness;
        protected global::System.Web.UI.WebControls.TextBox txtGuestFrequency;
        protected global::System.Web.UI.WebControls.CheckBox chkIsStudent;

        protected global::System.Web.UI.WebControls.FileUpload fileUploadProfilePic;

        protected global::System.Web.UI.WebControls.Button btnUpload;

        protected global::System.Web.UI.WebControls.Image imgProfile;

        protected global::System.Web.UI.WebControls.Label lblUploadStatus;


        protected global::System.Web.UI.WebControls.CheckBox chkHasHouse;
        protected global::System.Web.UI.WebControls.Panel pnlHouseInfo;

        protected global::System.Web.UI.WebControls.TextBox txtRent;
        protected global::System.Web.UI.WebControls.DropDownList ddlLocation; // New DropDownList for Location
        protected global::System.Web.UI.WebControls.TextBox txtRooms;
        protected global::System.Web.UI.WebControls.TextBox txtSaloons;
        protected global::System.Web.UI.WebControls.TextBox txtSurfaceArea;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.TextBox txtFlatFloor;
        protected global::System.Web.UI.WebControls.TextBox txtBuildingFloor;
        protected global::System.Web.UI.WebControls.TextBox txtBuildingFloorCount;
        protected global::System.Web.UI.WebControls.TextBox txtHeating;
        protected global::System.Web.UI.WebControls.TextBox txtBuildingAge;

        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}